### ISSUE TITLE
Небольшие замечания по коду

### ISSUE THREAD

**Issue by AlexZablotsky450501** [MarinaTitova/carsConfigurator#2]
В целом код доступный и понятный, но есть небольшие недостатки:
1) Это самый распространённый недостаток - нехватка комментов, особенно в тех местах где происходит добавление большого числа переменных, сложно понять за что каждая из них отвечает.
2)Также присутствуют огромные выражения, которые усложняют восприятие, поэтому лучше их разнести на несколько строк.
Пожелание: у тебя используется система авторизации с помощью логина и пароля, в целях безопасности сделай шифрацию отображения пароля в виде ***** при вводе, чтобы улучшить безопасность. p.s. но может быть это и лишнее*)

**Comment by MarinaTitova** [comment]
Алексей, благодарю за замечания) Все замечания по делу, исправим в ближайшее время.
