### ISSUE TITLE
Пара замечаний

### ISSUE THREAD

**Issue by NikolayKovzik450501** [MarinaTitova/carsConfigurator#5]
Код читаем, структурирован. Но несколько мелочей бросающихся в глаза есть:

1) Как отметил Алексей выше - мало комментариев, замедляет восприятие кода.
2) В некоторых функциях передаётся больше 5ти-6ти аргументов - такие функции не читабельны, это затрудняет понимание и поддержание работоспособности кода.
3) Использование тернарных операторов - тоже восприятие кода не улучшает.

В принципе всё, небольшие огрехи в табуляции думаю будут Автором в ближайшее время  и так устранены.

**Comment by MarinaTitova** [comment]
Николай,

С комментариями исправим, спасибо.
Насчёт функции с 6 параметрами - анимационная отрисовка, по-другому никак.
